name: Docker Pipeline CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./sauter_university
        file: ./sauter_university/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sauter-university-website:latest
